### ISSUE TITLE
Regex syntax error in check exclusion

### ISSUE THREAD

**Issue by shawnjefferson** [docker/docker-bench-security#330]
There's a syntax error in the check exclusion.  Trying to exclude 5.1 excludes 5.1, 5.10, 5.11, etc...

Adding a $ in line 126 of docker-bench-security.sh fixes it (quick testing):
 checkexcluded="$(echo "$checkexclude" | sed 's/,/$|/g')"

**Comment by konstruktoid** [comment]
Thanks @shawnjefferson, he documentation was a bit unclear. Try `-e check_5_1`.
I've updated the README to clarify this.

**Comment by shawnjefferson** [comment]
I believe this will still fail with the existing regex.  check_5_1 will match both check_5_1 and check_5_10, check_5_11, etc... won't it?  With my solution, which I think works, you can use both ways of exclusions: 5.1, 5.10, 5.11, or check_5_1, check_5_10, check_5_11

**Comment by konstruktoid** [comment]
You're absolutely correct, my bad.

` -e check_5_1$` works, but `checkexcluded="$(echo "$checkexclude" | sed 's/,/$|/g')"` doesn't.

**Comment by konstruktoid** [comment]
Updated with https://github.com/docker/docker-bench-security/pull/335

**Comment by konstruktoid** [comment]
#335 has been merged.

**Comment by konstruktoid** [comment]
Closing due to inactivity.
